import 'package:eventoury/web/Traveller/Details/frontend/Details.dart';
import 'package:get/get.dart';

class SubcategoriesController extends GetxController {
  final RxBool isMobileMenuOpen = false.obs;
  final RxString categoryTitle = 'Event'.obs;
  
  final RxList<Map<String, dynamic>> events = <Map<String, dynamic>>[].obs;

  // Define subcategories for different categories
  final Map<String, List<Map<String, dynamic>>> categorySubcategories = {
    'Activities': [
      {
        'title': 'Snorkeling',
        'subtitle': '245+ people',
        'rating': 4.7,
        'price': '\$89',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Surfing',
        'subtitle': '189+ people',
        'rating': 4.6,
        'price': '\$125',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Jet Ski',
        'subtitle': '156+ people',
        'rating': 4.8,
        'price': '\$199',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Para Sailing',
        'subtitle': '134+ people',
        'rating': 4.5,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Trekking',
        'subtitle': '278+ people',
        'rating': 4.4,
        'price': '\$149',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Flying Fish',
        'subtitle': '92+ people',
        'rating': 4.6,
        'price': '\$175',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'ATV',
        'subtitle': '165+ people',
        'rating': 4.7,
        'price': '\$119',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Cycling',
        'subtitle': '203+ people',
        'rating': 4.3,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Rafting',
        'subtitle': '187+ people',
        'rating': 4.8,
        'price': '\$145',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Banana Boat',
        'subtitle': '112+ people',
        'rating': 4.4,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Hot Air Balloon',
        'subtitle': '78+ people',
        'rating': 4.9,
        'price': '\$499',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Flyingboarding',
        'subtitle': '64+ people',
        'rating': 4.5,
        'price': '\$275',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Boat / Yacht Cruise',
        'subtitle': '89+ people',
        'rating': 4.8,
        'price': '\$599',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Helicopter Hire',
        'subtitle': '34+ people',
        'rating': 4.9,
        'price': '\$899',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Beer Bus',
        'subtitle': '156+ people',
        'rating': 4.2,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
    ],
    'Lessons/Classes': [
      {
        'title': 'Yoga Classes',
        'subtitle': '189+ people',
        'rating': 4.8,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Silver Jewellery Making Class',
        'subtitle': '67+ people',
        'rating': 4.6,
        'price': '\$125',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Stitching & Sewing Classes',
        'subtitle': '89+ people',
        'rating': 4.4,
        'price': '\$75',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Batik Painting',
        'subtitle': '134+ people',
        'rating': 4.7,
        'price': '\$95',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Coffee Making',
        'subtitle': '156+ people',
        'rating': 4.5,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Yadnya (Traditional Bali Craft)',
        'subtitle': '45+ people',
        'rating': 4.9,
        'price': '\$110',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Traditional Bali Music Classes',
        'subtitle': '78+ people',
        'rating': 4.6,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Cooking Classes',
        'subtitle': '267+ people',
        'rating': 4.8,
        'price': '\$89',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Surfing Classes',
        'subtitle': '198+ people',
        'rating': 4.7,
        'price': '\$135',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Pottery & Ceramic',
        'subtitle': '112+ people',
        'rating': 4.5,
        'price': '\$95',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Wood Carving',
        'subtitle': '89+ people',
        'rating': 4.6,
        'price': '\$115',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Batik Classes',
        'subtitle': '123+ people',
        'rating': 4.4,
        'price': '\$105',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Traditional Bali Dance Classes',
        'subtitle': '145+ people',
        'rating': 4.8,
        'price': '\$75',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Scooter Lessons',
        'subtitle': '203+ people',
        'rating': 4.3,
        'price': '\$55',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
    ],
    'Transportation': [
      {
        'title': 'Rent a Car',
        'subtitle': '456+ people',
        'rating': 4.5,
        'price': '\$45',
        'image': 'assets/home_screen/transport.jpg',
        'isFavorite': false,
      },
      {
        'title': 'Fast Boat & Yacht',
        'subtitle': '189+ people',
        'rating': 4.8,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Horse Carriage',
        'subtitle': '78+ people',
        'rating': 4.6,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Electric Bike',
        'subtitle': '234+ people',
        'rating': 4.4,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Rent a Scooter / Motor Cycle',
        'subtitle': '567+ people',
        'rating': 4.7,
        'price': '\$15',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Traditional Taxi',
        'subtitle': '334+ people',
        'rating': 4.2,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Ride Hailing',
        'subtitle': '789+ people',
        'rating': 4.3,
        'price': '\$20',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Cycle',
        'subtitle': '298+ people',
        'rating': 4.1,
        'price': '\$10',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
    ],
    'Guide': [
      {
        'title': 'English Speaking',
        'subtitle': '345+ people',
        'rating': 4.6,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Male Guides',
        'subtitle': '298+ people',
        'rating': 4.5,
        'price': '\$55',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Multi Lingual',
        'subtitle': '189+ people',
        'rating': 4.8,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Female Guides',
        'subtitle': '267+ people',
        'rating': 4.7,
        'price': '\$60',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
    ],
    'Accommodation': [
      {
        'title': 'Villas',
        'subtitle': '156+ people',
        'rating': 4.8,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Guest House',
        'subtitle': '234+ people',
        'rating': 4.5,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Home Stay',
        'subtitle': '298+ people',
        'rating': 4.6,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Budget Hotels',
        'subtitle': '567+ people',
        'rating': 4.2,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Hostel',
        'subtitle': '423+ people',
        'rating': 4.1,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Apartment',
        'subtitle': '189+ people',
        'rating': 4.4,
        'price': '\$125',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Capsule',
        'subtitle': '89+ people',
        'rating': 4.0,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
    ],
    'Entertainment': [
      {
        'title': 'Cinemas',
        'subtitle': '345+ people',
        'rating': 4.3,
        'price': '\$12',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Beach Clubs',
        'subtitle': '278+ people',
        'rating': 4.7,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Live Music Bars',
        'subtitle': '234+ people',
        'rating': 4.5,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Kareoke (KTV)',
        'subtitle': '189+ people',
        'rating': 4.4,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Shopping Malls',
        'subtitle': '567+ people',
        'rating': 4.2,
        'price': '\$0',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Theme Parks',
        'subtitle': '456+ people',
        'rating': 4.6,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Night Clubs',
        'subtitle': '298+ people',
        'rating': 4.1,
        'price': '\$95',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Night Bars',
        'subtitle': '312+ people',
        'rating': 4.3,
        'price': '\$55',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
    ],
    'Tourist Attraction Spots': [
      {
        'title': 'Bali Bird Park',
        'subtitle': '234+ people',
        'rating': 4.5,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Theme Park Studio Bali',
        'subtitle': '189+ people',
        'rating': 4.3,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Bom Water Park',
        'subtitle': '345+ people',
        'rating': 4.4,
        'price': '\$30',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Zoo',
        'subtitle': '278+ people',
        'rating': 4.2,
        'price': '\$28',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Shooting Gun Club',
        'subtitle': '89+ people',
        'rating': 4.1,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Handara Gate',
        'subtitle': '456+ people',
        'rating': 4.6,
        'price': '\$15',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Ubud Center',
        'subtitle': '567+ people',
        'rating': 4.7,
        'price': '\$10',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Nusa Penida',
        'subtitle': '689+ people',
        'rating': 4.8,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Gili Islands',
        'subtitle': '598+ people',
        'rating': 4.9,
        'price': '\$75',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Golf',
        'subtitle': '123+ people',
        'rating': 4.4,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Ubud Palace',
        'subtitle': '378+ people',
        'rating': 4.5,
        'price': '\$12',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Safari',
        'subtitle': '298+ people',
        'rating': 4.6,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Campuhan Ridge Walk',
        'subtitle': '234+ people',
        'rating': 4.5,
        'price': '\$5',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Botanical Garden',
        'subtitle': '167+ people',
        'rating': 4.3,
        'price': '\$18',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Seminyak Square',
        'subtitle': '289+ people',
        'rating': 4.2,
        'price': '\$8',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Nusa Lembongan',
        'subtitle': '445+ people',
        'rating': 4.7,
        'price': '\$55',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Lombok',
        'subtitle': '356+ people',
        'rating': 4.6,
        'price': '\$80',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Marine Park',
        'subtitle': '198+ people',
        'rating': 4.4,
        'price': '\$40',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Sacred Monkey Forest',
        'subtitle': '412+ people',
        'rating': 4.3,
        'price': '\$8',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Swings',
        'subtitle': '534+ people',
        'rating': 4.5,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Upside Down Museum',
        'subtitle': '156+ people',
        'rating': 4.1,
        'price': '\$22',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Banjar Hot Spring',
        'subtitle': '267+ people',
        'rating': 4.4,
        'price': '\$15',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Garuda Wisnu Kencana',
        'subtitle': '389+ people',
        'rating': 4.6,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Art Galleries',
        'subtitle': '145+ people',
        'rating': 4.2,
        'price': '\$12',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Nusa Ceningan',
        'subtitle': '234+ people',
        'rating': 4.5,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Menjangan Island',
        'subtitle': '178+ people',
        'rating': 4.7,
        'price': '\$95',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Temples',
        'subtitle': '623+ people',
        'rating': 4.8,
        'price': '\$20',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Rice Terrace',
        'subtitle': '498+ people',
        'rating': 4.7,
        'price': '\$12',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Beaches',
        'subtitle': '789+ people',
        'rating': 4.6,
        'price': '\$5',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Water Falls',
        'subtitle': '445+ people',
        'rating': 4.5,
        'price': '\$8',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Volcanoes',
        'subtitle': '356+ people',
        'rating': 4.8,
        'price': '\$120',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Museums',
        'subtitle': '198+ people',
        'rating': 4.3,
        'price': '\$15',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Art Markets',
        'subtitle': '334+ people',
        'rating': 4.2,
        'price': '\$5',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Lakes',
        'subtitle': '278+ people',
        'rating': 4.4,
        'price': '\$10',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Komodo Island',
        'subtitle': '234+ people',
        'rating': 4.9,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
    ],
    'Fitness and Wellbeing': [
      {
        'title': 'Gym',
        'subtitle': '456+ people',
        'rating': 4.3,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Pilates',
        'subtitle': '234+ people',
        'rating': 4.6,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Flower Bath Ritual Healing',
        'subtitle': '156+ people',
        'rating': 4.8,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Spiritual Meditation',
        'subtitle': '189+ people',
        'rating': 4.7,
        'price': '\$55',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bali Padel',
        'subtitle': '98+ people',
        'rating': 4.4,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Traditional SPA',
        'subtitle': '345+ people',
        'rating': 4.7,
        'price': '\$95',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Sound Healing',
        'subtitle': '123+ people',
        'rating': 4.5,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Spas',
        'subtitle': '567+ people',
        'rating': 4.6,
        'price': '\$75',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
    ],
    'Cultural, Heritage, and History': [
      {
        'title': 'Penglipuran Village',
        'subtitle': '298+ people',
        'rating': 4.7,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Garuda Wisnu Kencana Cultural Park',
        'subtitle': '456+ people',
        'rating': 4.6,
        'price': '\$35',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Trunyan Village',
        'subtitle': '134+ people',
        'rating': 4.2,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Tenganan Village',
        'subtitle': '167+ people',
        'rating': 4.5,
        'price': '\$30',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'MAS Village',
        'subtitle': '189+ people',
        'rating': 4.4,
        'price': '\$20',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Kertalangu Cultural Village',
        'subtitle': '123+ people',
        'rating': 4.3,
        'price': '\$28',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Pesa Lakan Cultural Village',
        'subtitle': '98+ people',
        'rating': 4.1,
        'price': '\$22',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
    ],
    'Tickets': [
      {
        'title': 'Theme Parks',
        'subtitle': '456+ people',
        'rating': 4.5,
        'price': '\$45',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Museums',
        'subtitle': '234+ people',
        'rating': 4.3,
        'price': '\$18',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Tourist Attractions',
        'subtitle': '678+ people',
        'rating': 4.6,
        'price': '\$25',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Beach Clubs & Other Clubs',
        'subtitle': '345+ people',
        'rating': 4.4,
        'price': '\$85',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Cinemas',
        'subtitle': '398+ people',
        'rating': 4.2,
        'price': '\$12',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Activities',
        'subtitle': '567+ people',
        'rating': 4.7,
        'price': '\$65',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
    ],
    'Events': [
      {
        'title': 'Romantic Dinner',
        'subtitle': '234+ people',
        'rating': 4.7,
        'price': '\$125',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Weddings',
        'subtitle': '89+ people',
        'rating': 4.9,
        'price': '\$2999',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bachelor Parties',
        'subtitle': '156+ people',
        'rating': 4.4,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Honeymoon',
        'subtitle': '167+ people',
        'rating': 4.8,
        'price': '\$1299',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Birthdays',
        'subtitle': '298+ people',
        'rating': 4.5,
        'price': '\$199',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Romantic Proposals',
        'subtitle': '78+ people',
        'rating': 4.9,
        'price': '\$599',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Baby Shower',
        'subtitle': '134+ people',
        'rating': 4.6,
        'price': '\$249',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
    ],
    'Tour Packages': [
      {
        'title': 'Honey Moon Tours',
        'subtitle': '234+ people',
        'rating': 4.9,
        'price': '\$1599',
        'image': 'assets/home_screen/tour_packages.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Family Tours',
        'subtitle': '456+ people',
        'rating': 4.6,
        'price': '\$599',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Wellbeing Tours',
        'subtitle': '189+ people',
        'rating': 4.7,
        'price': '\$899',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bar Hopping Tours',
        'subtitle': '167+ people',
        'rating': 4.3,
        'price': '\$89',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Couple Tours',
        'subtitle': '298+ people',
        'rating': 4.8,
        'price': '\$1199',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Adventure Tours',
        'subtitle': '389+ people',
        'rating': 4.7,
        'price': '\$799',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Food Tours',
        'subtitle': '345+ people',
        'rating': 4.5,
        'price': '\$129',
        'image': 'assets/onboarding_images/onboarding_6.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Cultural & Heritage Tours',
        'subtitle': '278+ people',
        'rating': 4.6,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Bag Packer Tours',
        'subtitle': '234+ people',
        'rating': 4.2,
        'price': '\$199',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Spiritual Tours',
        'subtitle': '156+ people',
        'rating': 4.8,
        'price': '\$399',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Activity Tours',
        'subtitle': '423+ people',
        'rating': 4.5,
        'price': '\$349',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Corporate Tours',
        'subtitle': '123+ people',
        'rating': 4.4,
        'price': '\$999',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
    ],
    'VIP Protocol': [
      {
        'title': 'VIP Protocol from Plane to Checkout',
        'subtitle': '45+ people',
        'rating': 4.9,
        'price': '\$1999',
        'image': 'assets/onboarding_images/onboarding_4.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Immigration & Customs Assistance',
        'subtitle': '67+ people',
        'rating': 4.8,
        'price': '\$299',
        'image': 'assets/onboarding_images/onboarding_1.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'VIP Lounge Welcome Snacks & Drinks',
        'subtitle': '89+ people',
        'rating': 4.6,
        'price': '\$149',
        'image': 'assets/onboarding_images/onboarding_2.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'Police Protocol to Avoid Traffic',
        'subtitle': '34+ people',
        'rating': 4.7,
        'price': '\$599',
        'image': 'assets/onboarding_images/onboarding_3.jpeg',
        'isFavorite': false,
      },
      {
        'title': 'VIP Luxury Vehicle',
        'subtitle': '78+ people',
        'rating': 4.5,
        'price': '\$399',
        'image': 'assets/onboarding_images/onboarding_5.jpeg',
        'isFavorite': false,
      },
    ],
  };

  @override
  void onInit() {
    super.onInit();
    // Set initial events based on category
    updateEventsForCategory();
  }

  void updateEventsForCategory() {
    // Get subcategories for the current category, or use Events as default
    final subcategories = categorySubcategories[categoryTitle.value] ?? categorySubcategories['Events']!;
    events.assignAll(subcategories);
  }

  void toggleMobileMenu() {
    isMobileMenuOpen.value = !isMobileMenuOpen.value;
  }

  void toggleFavorite(int index) {
    events[index]['isFavorite'] = !events[index]['isFavorite'];
    events.refresh();
  }

  void setCategoryTitle(String title) {
    categoryTitle.value = title;
    updateEventsForCategory();
  }

  void onEventTap(String eventTitle) {
    // Find the event data
    final event = events.firstWhere((e) => e['title'] == eventTitle);
    
    // Navigate to details screen with event data
    Get.to(() => DetailsScreen(
      title: event['title'],
      location: 'Bali, Indonesia',
      country: 'Indonesia',
      rating: event['rating'],
      reviewCount: int.parse(event['subtitle'].replaceAll(RegExp(r'[^0-9]'), '')),
      price: event['price'],
    ));
  }
}