// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj1d1W2aLaglfR6WkhxsToGVmJrviMpkE',
    appId: '1:265794852882:web:e11d77e5a8c920203820cb',
    messagingSenderId: '265794852882',
    projectId: 'eventoury-a0645',
    authDomain: 'eventoury-a0645.firebaseapp.com',
    storageBucket: 'eventoury-a0645.firebasestorage.app',
    measurementId: 'G-9CBLBHHSSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_36FHXooiIQ3UJwia6WzuixE5kmmewc0',
    appId: '1:265794852882:android:961ec0fe057d9ce93820cb',
    messagingSenderId: '265794852882',
    projectId: 'eventoury-a0645',
    storageBucket: 'eventoury-a0645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiZNY_i-w6DAyxN4MwelYrM4niy6w8Bzs',
    appId: '1:265794852882:ios:895ca7948d9cf3293820cb',
    messagingSenderId: '265794852882',
    projectId: 'eventoury-a0645',
    storageBucket: 'eventoury-a0645.firebasestorage.app',
    iosBundleId: 'com.example.eventoury',
  );
}
